// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class UIImage;

SWIFT_CLASS("_TtC7BmobSDK8BmobFile")
@interface BmobFile : NSObject
/**
  上传图片
*/
- (void)upImageWithImage:(UIImage * _Nonnull)image :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  上传文件
  fileType 文件类型 如 image/jpeg
  fileName 文件名
  filePath 文件路径
*/
- (void)upFile:(NSString * _Nonnull)fileType :(NSString * _Nonnull)fileName :(NSString * _Nonnull)filePath :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  删除文件
  fileUrl 是上传之后返回的url，然后去掉前面的域名
  cdnName 是上传之后返回的
*/
- (void)deletFile:(NSString * _Nonnull)fileUrl :(NSString * _Nonnull)cdnName mathFunction:(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  批量删除文件
  fileUrlArray 是上传之后返回的url的数组，然后每个url去掉前面的域名
  cdnName 是上传之后返回的
*/
- (void)deleteMoreFile:(NSArray<NSString *> * _Nonnull)fileUrlArray :(NSString * _Nonnull)cdnName mathFunction:(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7BmobSDK9BmobQuery")
@interface BmobQuery : NSObject
/**
  限制返回数据的个数
*/
@property (nonatomic) NSInteger limit;
/**
  跳过指定数量的数据
*/
@property (nonatomic) NSInteger skip;
/**
  创建BmobQuery对象
*/
+ (BmobQuery * _Nullable)queryWithTabNameWithTabName:(NSString * _Nonnull)tabName;
/**
  添加一条数据
*/
- (void)addOneDataWithDataDic:(NSDictionary<NSString *, id> * _Nonnull)dataDic :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  更新一条数据
*/
- (void)upOneDataWithObjectId:(NSString * _Nonnull)objectId dataDic:(NSDictionary<NSString *, id> * _Nonnull)dataDic :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  删除一条数据
*/
- (void)deleteOneDataWithObjectId:(NSString * _Nonnull)objectId :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  查询单条数据
  objectId 数据对应ID
*/
- (void)searchOneDataWithObjectId:(NSString * _Nonnull)objectId :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  查询全部数据没有查询条件
*/
- (void)searchAllData:(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  条件查询
  可多条件
  全部放入searchDic中
*/
- (void)searchDataWithWhereWithSearchDic:(NSDictionary<NSString *, id> * _Nonnull)searchDic :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7BmobSDK7BmobSDK")
@interface BmobSDK : NSObject
+ (BmobSDK * _Nonnull)shareBmobSDK;
/**
  注册应用
*/
- (void)registAppWithAppID:(NSString * _Nonnull)appID restFulKey:(NSString * _Nonnull)restFulKey;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7BmobSDK8BmobUser")
@interface BmobUser : NSObject
- (void)setNameWithUserName:(NSString * _Nonnull)userName;
- (void)setPassWordWithPassword:(NSString * _Nonnull)password;
- (void)setUserInfoWithValue:(id _Nonnull)value key:(NSString * _Nonnull)key;
/**
  注册用户
*/
- (void)register:(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  登录用户
*/
- (void)loginWithUsername:(NSString * _Nonnull)username password:(NSString * _Nonnull)password :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  获取当前用户信息
*/
- (void)currentUser:(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  更新当前用户信息
*/
- (void)upDateUesrInfoWithDataDic:(NSDictionary<NSString *, id> * _Nonnull)dataDic :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  查询所有用户
  searchDic 查询的限制
  如[“limit”:“12”,“skip”:“10”]设置返回数据个数和跳过多少条数据
*/
- (void)searchAllUserWithSearchDic:(NSDictionary<NSString *, NSString *> * _Nonnull)searchDic :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
/**
  修改密码
  新老密码方式修改
*/
- (void)updatePasswordWithOldPassword:(NSString * _Nonnull)oldPassword newPassword:(NSString * _Nonnull)newPassword :(void (^ _Nonnull)(id _Nonnull, BOOL, NSError * _Nullable))mathFunction;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
